server.port=8081
spring.mongodb.uri=mongodb+srv://admin:admin123@docvault.guuxgkb.mongodb.net/docvault
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy